### ISSUE TITLE
Js to Gradle

### ISSUE THREAD

**Issue by safiresh** [ninetwozero/gradle-to-js#2]
Guide me . i want to change some value in gradle file . I user this library for parse the file & changed  value too. but i can't write a file . ican't use JSON.stringnify .. its not support gradle file

**Comment by karllindmark** [comment]
Hi Sathish!

As gradle-to-js is "quick & dirty" in the sense that it might not handle
all the various constructs correctly, it would probably be a bad idea to
try to use the structure it creates to generate a new build file.

I don't have access to a computer at the moment so I can't really do some
digging on my end, but let me know if you do develop the functionality
needed to generate the gradle file from the previously created object
structure. ☺️

**Comment by safiresh** [comment]
@karllindmark  I am also done "quick & dirty" way only. kindly check below npm module. I alter little bit formations only 

npm install gradlejs --save

https://github.com/safiresh/gradle-to-js

All parameter maintain with string only. so if we provide string double time qoutes . Its quick things i done on that. But We need to define type based object read & write :(

**Comment by karllindmark** [comment]
Hey @safiresh! 

After giving it some thought (more like, 10 months worth of it - sorry!) I kinda feel like this might be "out of scope" for the current state of `gradle-to-js`. 

It would probably require a less "quick & dirty" parser to parse values as their appropriate types, and return them the same way afterwards.

Let me know if you have any further thoughts on this - I'll just close this issue for now. :-)
