### ISSUE TITLE
read value of some property in gradle file

### ISSUE THREAD

**Issue by iadcg** [ninetwozero/gradle-to-js#22]
Can this lib ready the value of a property or key in a gradle file?

For example:
android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }

    defaultConfig {
        applicationId "com.axinan.galadriel"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0.0"
        multiDexEnabled true
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
}

i want to get the value of multiDexEnabled. 
Btw, Im working on a react native android app here

**Comment by karllindmark** [comment]
Yeah, should be achievable with something like:

parsedResult['android']['defaultConfig']['multiDexEnabled'], if I'm not
mistaken.

Can you verify?

Best regards,
Karl Lindmark

**Comment by karllindmark** [comment]
Hey @iadcg, did my proposed solution work? :-)
